### ISSUE TITLE
cat021/131 and 271 have some errors

### ISSUE THREAD

**Issue by lhguo-grabel** [vilamarcc/AsterixDecoderPGTA#2]
the code for 131
{
this.LatitudeWGS_HR = Math.Round(1000 * this.ComputeComplementoA2(lat) * (180 / Math.Pow(2, **_31_**))) / 1000; this.LongitudeWGS_HR = Math.Round(1000 * this.ComputeComplementoA2(lon) * (180 / Math.Pow(2, **_31_**))) / 1000;
}
the 31 must be 30.
the code for 271
{
 if(bits1.Substring(7,1)=="1")
            {
                //octeto 2 -hexadecimal
                string octeto2 = paquete[pos + cont];

                //octeto 2 -binari
                string bits2 = Convert.ToString(Convert.ToInt32(octeto2, 16), 2).PadLeft(8, '0');

                //llegim octeto 2 - First Extension
                this.LmasW = Convert.ToInt32(bits2.Substring(4, 4), 2);
                **_cont++_**
               }
} it missed cont++

**Comment by vilamarcc** [comment]
Hello,
Sorry for the delay I just realised you opened the issue, I know I'm a year late but I think it's worth while addressing this.

1. On item I021/131: The change you proposed is correct, I think the error is due to the fact that the code is based on an older EUROCONTROL-SPEC document and since this was coded maybe it has changed from 2^31 to 2^30.
2. On item I021/271: The change you propose is correct and it's something that we missed back in the day as this extension was not triggered on our testing data file messages.

Thank you for the issue opened, I will update the code and credit you.
Also I want to let you know that this AsterixDecoder is an old university project and probably wont be updated in the future with the current documentation of the Asterix.
Again thanks for letting me know, I will close the issue.
Kind regards
